"""Planetary Facts from Our Solar System
Note that some values were converted to desired units.
Credit: https://nssdc.gsfc.nasa.gov/planetary/factsheet/
"""
planetary_facts = {
    "Mercury": {
        "mass": 3.3e+23,
        "radius": 2439.5,
        "density": 5427,
        "gravity": 3.7,
        "escape velocity": 4.3,
        "rotation period": 1407.6,
        "length of day": 4222.6,
        "distance from sun": 5.79e+07,
        "perihelion": 4.6e+07,
        "aphelion": 6.98e+07,
        "orbital period": 88.0,
        "orbital velocity": 47.4,
        "orbital inclination": 7.0,
        "orbital eccentricity": 0.205,
        "obliquity to orbit": 0.034,
        "mean temperature": 440,
        "surface pressure": 0,
        "number of moons": 0,
        "ring system": False,
        "global magnetic field": True
    },
    "Venus": {
        "mass": 4.87e+24,
        "radius": 6052,
        "density": 5243,
        "gravity": 8.9,
        "escape velocity": 10.4,
        "rotation period": -5832.5,
        "length of day": 2802.0,
        "distance from sun": 1.082e+08,
        "perihelion": 1.075e+08,
        "aphelion": 1.089e+08,
        "orbital period": 224.7,
        "orbital velocity": 35.0,
        "orbital inclination": 3.4,
        "orbital eccentricity": 0.007,
        "obliquity to orbit": 177.4,
        "mean temperature": 737,
        "surface pressure": 92,
        "number of moons": 0,
        "ring system": False,
        "global magnetic field": False
    },
    "Earth": {
        "mass": 5.97e+24,
        "radius": 6378.0,
        "density": 5514,
        "gravity": 9.8,
        "escape velocity": 11.2,
        "rotation period": 23.9,
        "length of day": 24.0,
        "distance from sun": 1.496e+08,
        "perihelion": 1.471e+08,
        "aphelion": 1.521e+08,
        "orbital period": 365.2,
        "orbital velocity": 29.8,
        "orbital inclination": 0.0,
        "orbital eccentricity": 0.017,
        "obliquity to orbit": 23.4,
        "mean temperature": 288,
        "surface pressure": 1,
        "number of moons": 1,
        "ring system": False,
        "global magnetic field": True
    },
    "Moon": {
        "mass": 7.3e+22,
        "radius": 1737.5,
        "density": 3340,
        "gravity": 1.6,
        "escape velocity": 2.4,
        "rotation period": 655.7,
        "length of day": 708.7,
        "distance from earth": 3.84e+05,
        "perihelion": 3.63e+05,
        "aphelion": 4.06e+05,
        "orbital period": 27.3,
        "orbital velocity": 1.0,
        "orbital inclination": 5.1,
        "orbital eccentricity": 0.055,
        "obliquity to orbit": 6.7,
        "mean temperature": 253,
        "surface pressure": 0,
        "number of moons": 0,
        "ring system": False,
        "global magnetic field": False
    },
    "Mars": {
        "mass": 6.42e+23,
        "radius": 3396.0,
        "density": 3933,
        "gravity": 3.7,
        "escape velocity": 5.0,
        "rotation period": 24.6,
        "length of day": 24.7,
        "distance from sun": 2.279e+08,
        "perihelion": 2.066e+08,
        "aphelion": 2.492e+08,
        "orbital period": 687.0,
        "orbital velocity": 24.1,
        "orbital inclination": 1.9,
        "orbital eccentricity": 0.094,
        "obliquity to orbit": 25.2,
        "mean temperature": 208,
        "surface pressure": 0.01,
        "number of moons": 2,
        "ring system": False,
        "global magnetic field": False
    },
    "Jupiter": {
        "mass": 1.898e+27,
        "radius": 71492.0,
        "density": 1326,
        "gravity": 23.1,
        "escape velocity": 59.5,
        "rotation period": 9.9,
        "length of day": 9.9,
        "distance from sun": 7.786e+08,
        "perihelion": 7.405e+08,
        "aphelion": 8.166e+08,
        "orbital period": 4331,
        "orbital velocity": 13.1,
        "orbital inclination": 1.3,
        "orbital eccentricity": 0.049,
        "obliquity to orbit": 3.1,
        "mean temperature": 163,
        "surface pressure": "unknown",
        "number of moons": 79,
        "ring system": True,
        "global magnetic field": True
    },
    "Saturn": {
        "mass": 5.68e+26,
        "radius": 60268.0,
        "density": 687,
        "gravity": 9.0,
        "escape velocity": 35.5,
        "rotation period": 10.7,
        "length of day": 10.7,
        "distance from sun": 1.43353e+09,
        "perihelion": 1.3526e+09,
        "aphelion": 1.5145e+09,
        "orbital period": 10747,
        "orbital velocity": 9.7,
        "orbital inclination": 2.5,
        "orbital eccentricity": 0.057,
        "obliquity to orbit": 26.7,
        "mean temperature": 133,
        "surface pressure": "unknown",
        "number of moons": 62,
        "ring system": True,
        "global magnetic field": True
    },
    "Uranus": {
        "mass": 8.68e+25,
        "radius": 25559.0,
        "density": 1271,
        "gravity": 8.7,
        "escape velocity": 21.3,
        "rotation period": -17.2,
        "length of day": 17.2,
        "distance from sun": 2.8725e+09,
        "perihelion": 2.7413e+09,
        "aphelion": 3.0036e+09,
        "orbital period": 30589,
        "orbital velocity": 6.8,
        "orbital inclination": 0.8,
        "orbital eccentricity": 0.046,
        "obliquity to orbit": 97.8,
        "mean temperature": 78,
        "surface pressure": "unknown",
        "number of moons": 27,
        "ring system": True,
        "global magnetic field": True
    },
    "Neptune": {
        "mass": 1.02e+26,
        "radius": 24764.0,
        "density": 1638,
        "gravity": 11.0,
        "escape velocity": 23.5,
        "rotation period": 16.1,
        "length of day": 16.1,
        "distance from sun": 4.4951e+09,
        "perihelion": 4.4445e+09,
        "aphelion": 4.5457e+09,
        "orbital period": 59800,
        "orbital velocity": 5.4,
        "orbital inclination": 1.8,
        "orbital eccentricity": 0.011,
        "obliquity to orbit": 28.3,
        "mean temperature": 73,
        "surface pressure": "unknown",
        "number of moons": 14,
        "ring system": True,
        "global magnetic field": True
    },
    "Pluto": {
        "mass": 1.46e+22,
        "radius": 1185.0,
        "density": 2095,
        "gravity": 0.7,
        "escape velocity": 1.3,
        "rotation period": -153.3,
        "length of day": 153.3,
        "distance from sun": 5.9064e+09,
        "perihelion": 4.4368e+09,
        "aphelion": 7.3759e+09,
        "orbital period": 90560,
        "orbital velocity": 4.7,
        "orbital inclination": 17.2,
        "orbital eccentricity": 0.244,
        "obliquity to orbit": 122.5,
        "mean temperature": 48,
        "surface pressure": 0.00001,
        "number of moons": 5,
        "ring system": False,
        "global magnetic field": False
    },
}


"""Sun Facts
Credit: https://nssdc.gsfc.nasa.gov/planetary/factsheet/sunfact.html
"""
sun_facts = {
    "mass": 1.9885e+30,
    "radius": 695700,
    "density": 1408,
    "gravity": 274,
    "escape velocity": 617.6,
    "rotation period": 609.12,
    "mean temperature": 5778,
    "luminosity": 3.828e+26,
    "obliquity to orbit": 7.25,
    "global magnetic field": True
}


"""Schwarzschild Radius and Density Examples
Note that these are heavily rounded calculations.
Credit: https://en.wikipedia.org/wiki/Schwarzschild_radius
"""
schwarzschild_facts = {
    "Milky Way": {
        "mass": 1.6e+42,
        "radius": 2.4e+15,
        "density": 0.000029
    },
    "SMBH in NGC 4889": {
        "mass": 4.2e+40,
        "radius": 6.2e+13,
        "density": 0.042
    },
    "SMBH in Andromeda Galaxy": {
        "mass": 3.4e+38,
        "radius": 5.0e+11,
        "density": 640
    },
    "Sagittarius A* (SMBH)": {
        "mass": 8.2e+36,
        "radius": 1.2e+10,
        "density": 1.1e+06
    },
    "Planck mass": {
        "mass": 2.18e-08,
        "radius": 3.23e-35,
        "density": 1.54e+95
    },
}
